language: c++

matrix:
  include:
  - os: linux	
  addons:	
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - g++-5
      env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq zlib1g-dev
- sudo apt-get install -qq mpich2
- sudo apt-get install -qq gsl-bin
- sudo apt-get install -qq libgsl0-dev
- sudo apt-get install -qq libgsl0ldbl
- sudo apt-get install -qq liblua5.2
- sudo apt-get install -qq liblua5.2-dev
- sudo apt-get install -qq libhdf5-dev

script:
- cp make.inc.template make.inc
- make clean
- make nulib
- make all