language: c++

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq zlib1g-dev
- sudo apt-get install -qq mpich2
- sudo apt-get install -qq gsl-bin
- sudo apt-get install -qq libgsl0-dev
- sudo apt-get install -qq libgsl0ldbl
- sudo apt-get install -qq lua5.2
- sudo apt-get install -qq libhdf5-serial-dev

script:
- make clean
- make