language: c++

os:
- linux

dist: trusty

sudo: true

python:
- 3.6

notifications:
  email:
    recipients:
      - sricher@ncsu.edu
    on_success: change
    on_failure: always

cache:
  directories:
  - external/hdf5
  - external/lua

addons:	
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gfortran-5
    - mpich2
    - libmpich-dev
    - gsl-bin
    - libgsl0-dev
    - libgsl0ldbl
    - zlib1g-dev
    - python3
    - python3-numpy
    - python3-scipy
    - python3-h5py
    - python3-matplotlib
    - gnuplot
    env:
    - CC=gcc-5
    - CXX=g++-5
    - F90=gfortran-5

install:
- cp make.inc.template make.inc
- make hdf5 &>> dependency_log.txt
- make nulib
- make lua &>> dependency_log.txt

script:
- make clean; DEBUG=1 NDIMS=0 DO_GR=0 make all -j4
- make clean; DEBUG=1 NDIMS=1 DO_GR=0 make all -j4
- make -C tests/spherical_emis
- make -C tests/schwarzschild_path_test
- make clean; DEBUG=1 NDIMS=2 DO_GR=0 make all -j4
- make clean; DEBUG=1 NDIMS=3 DO_GR=0 make all -j4
- make clean; DEBUG=1 NDIMS=0 DO_GR=1 make all -j4
- make clean; DEBUG=1 NDIMS=1 DO_GR=1 make all -j4
- make -C tests/spherical_emis
- make -C tests/schwarzschild_path_test
- make clean; DEBUG=1 NDIMS=2 DO_GR=1 make all -j4
- make clean; DEBUG=1 NDIMS=3 DO_GR=1 make all -j4
