language: c++

os:
- linux

dist: trusty

sudo: true

python:
- 3.6

notifications:
  email:
    recipients:
      - sricher@ncsu.edu
    on_success: change
    on_failure: always

cache:
  directories:
  - external

addons:	
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gfortran-5
    - mpich2
    - libmpich-dev
    - gsl-bin
    - libgsl0-dev
    - libgsl0ldbl
    - zlib1g-dev
    - python3
    - python3-numpy
    - python3-scipy
    - python3-h5py
    - python3-matplotlib
    - gnuplot
    - bzip2
    env:
    - CC=gcc-5
    - CXX=g++-5
    - F90=gfortran-5
    - OMP_NUM_THREADS=4

install:
- cp make.inc.template make.inc
- make hdf5 &>> dependency_log.txt
- make nulib
- make lua &>> dependency_log.txt
- wget https://stellarcollapse.org/~evanoc/Hempel_SFHoEOS_rho222_temp180_ye60_version_1.1_20120817.h5.bz2; bunzip2 Hempel_SFHoEOS_rho222_temp180_ye60_version_1.1_20120817.h5.bz2; mv Hempel_SFHoEOS_rho222_temp180_ye60_version_1.1_20120817.h5 external
- sed -i 's/eos_table_name.*/eos_table_name=\.\.\/Hempel_SFHoEOS_rho222_temp180_ye60_version_1\.1_20120817\.h5/' external/NuLib/parameters
- cd external/NuLib; ./make_table_example > output.txt; mv NuLib*.h5 NuLib.h5; cd $TRAVIS_BUILD_DIR


script:
- make clean; DEBUG=1 NDIMS=0 DO_GR=0 make all -j4
- make -C tests/inelastic_scatter
- make -C tests/blackbody
- make clean; DEBUG=1 NDIMS=1 DO_GR=0 make all -j4
- make -C tests/spherical_emis
- make -C tests/schwarzschild_path_test
- make -C tests/neutrino_oven
- make -C tests/diffusion
- make clean; DEBUG=1 NDIMS=2 DO_GR=0 make all -j4
- make clean; DEBUG=1 NDIMS=3 DO_GR=0 make all -j4
- make clean; DEBUG=1 NDIMS=0 DO_GR=1 make all -j4
- make -C tests/inelastic_scatter
- make -C tests/blackbody
- exe/MetricTest
- make clean; DEBUG=1 NDIMS=1 DO_GR=1 make all -j4
- make -C tests/spherical_emis
- make -C tests/schwarzschild_path_test
- make -C tests/neutrino_oven
- make -C tests/diffusion
- make clean; DEBUG=1 NDIMS=2 DO_GR=1 make all -j4
- make clean; DEBUG=1 NDIMS=3 DO_GR=1 make all -j4
