language: c++

os:
- linux

dist: trusty

sudo: false

cache:
- external/hdf5

addons:	
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gfortran-5
    - mpich2
    - libmpich-dev
    - gsl-bin
    - libgsl0-dev
    - libgsl0ldbl
    - zlib1g-dev
    env:
    - CC=gcc-5
    - CXX=g++-5
    - F90=gfortran-5

script:
- cp make.inc.template make.inc
- make hdf5
- make nulib
- make lua
- make all