language: c++

os:
- linux

dist: trusty

sudo: false

addons:	
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gfortran-5
    - mpich2
    - libmpich-dev
    - gsl-bin
    - libgsl0-dev
    - libgsl0ldbl
    - zlib1g-dev
    env:
    - CC=gcc-5
    - CXX=g++-5
    - F90=gfortran-5

script:
- cp make.inc.template make.inc
- make hdf5
- make nulib
- make lua
- make clean; DEBUG=0 NDIMS=0 DO_GR=0 make
- make clean; DEBUG=0 NDIMS=1 DO_GR=0 make
- make clean; DEBUG=0 NDIMS=2 DO_GR=0 make
- make clean; DEBUG=0 NDIMS=3 DO_GR=0 make
- make clean; DEBUG=0 NDIMS=0 DO_GR=1 make
- make clean; DEBUG=0 NDIMS=1 DO_GR=1 make
- make clean; DEBUG=0 NDIMS=2 DO_GR=1 make
- make clean; DEBUG=0 NDIMS=3 DO_GR=1 make
- make clean; DEBUG=1 NDIMS=0 DO_GR=0 make
- make clean; DEBUG=1 NDIMS=1 DO_GR=0 make
- make clean; DEBUG=1 NDIMS=2 DO_GR=0 make
- make clean; DEBUG=1 NDIMS=3 DO_GR=0 make
- make clean; DEBUG=1 NDIMS=0 DO_GR=1 make
- make clean; DEBUG=1 NDIMS=1 DO_GR=1 make
- make clean; DEBUG=1 NDIMS=2 DO_GR=1 make
- make clean; DEBUG=1 NDIMS=3 DO_GR=1 make
