language: c++

os:
- linux
dist: trusty
sudo: false

addons:	
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - mpich2
    - libmpich-dev
    - gsl-bin
    - libgsl0-dev
    - libgsl0ldbl
    - liblua5.2
    - liblua5.2-dev
    - libhdf5-dev
    - zlib1g-dev

script:
- cp make.inc.template make.inc
- make clean
- make nulib
- make all